# Generated by Django 3.1.3 on 2020-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_idf', '0002_recommendationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationmodel',
            name='paper_id',
            field=models.IntegerField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
